import CryptoJS from "crypto-js";

// Encrypting Secret Key Json
// This key can be generated by going to credentials then keys then generate new
const jsonKey = {
  type: "",
  project_id: "",
  private_key_id: "",
  private_key: "",
  client_email: "",
  client_id: "",
  auth_uri: "",
  token_uri: "",
  auth_provider_x509_cert_url: "",
  client_x509_cert_url: "",
};

const secret = "mysecret";

const encryptedData = CryptoJS.AES.encrypt(JSON.stringify(jsonKey), secret);

console.log(encryptedData.toString());

const decryptedData = CryptoJS.AES.decrypt(encryptedData, secret);
const decryptedDataParsed = JSON.parse(
  decryptedData.toString(CryptoJS.enc.Utf8)
);

console.log(decryptedDataParsed);
